# Don't change this! Version used to track needed updates.
version = 1
leaderRedAura = true
reinforcementSpawnSounds = true
spawnSoundVolume = 1.0
onlyLeaderSpawnsReinforcements = false
noLeaderFromSpawners = false
noReinforcementsFromSpawners = false
leaderMaxSpawnChance = 0.05