#List of ranks
[[ranks]]
	tier = 0
	numAffixes = 0
	defaultColor = "#FFFFFF"
	weight = 9500
	growthFactor = 1
	effects = []
	presetAffixes = []
#List of ranks
[[ranks]]
	tier = 1
	numAffixes = 1
	defaultColor = "#00FF00"
	weight = 300
	growthFactor = 1
	effects = []
	presetAffixes = []
#List of ranks
[[ranks]]
	tier = 2
	numAffixes = 2
	defaultColor = "#FFFF00"
	weight = 200
	growthFactor = 4
	effects = []
	presetAffixes = []
#List of ranks
[[ranks]]
	tier = 3
	numAffixes = 3
	defaultColor = "#FFD700"
	weight = 75
	growthFactor = 7
	effects = []
	presetAffixes = []
#List of ranks
[[ranks]]
	tier = 4
	numAffixes = 4
	defaultColor = "#FF5555"
	weight = 50
	growthFactor = 10
	effects = []
	presetAffixes = []
#List of ranks
[[ranks]]
	tier = 5
	numAffixes = 5
	defaultColor = "#FF4500"
	weight = 25
	growthFactor = 16
	effects = []
	presetAffixes = []
#List of ranks
[[ranks]]
	tier = 6
	numAffixes = 6
	defaultColor = "#CC33FF"
	weight = 15
	growthFactor = 20
	effects = []
	presetAffixes = []
#List of ranks
[[ranks]]
	tier = 7
	numAffixes = 7
	defaultColor = "#8A2BE2"
	weight = 8
	growthFactor = 25
	effects = []
	presetAffixes = []
