#Icarus Wings Config File
[config]
	#Speed factor for Synapse Wings
	# Default: 1.0
	# Range: 0.0 ~ 1.7976931348623157E308
	wings_speed_mod = 1.0
	#Transport card use permission level
	# Default: 2
	# Range: 0 ~ 3
	transport_card_permission_level = 2
	#Does Demeter projectile change terrain
	allow_demeter_change_terrain = false
