#Totemic server configuration settings. These settings are world specific and are synced from the server to clients.
[server]
	#List of Ceremonies that should be disabled. Note that disabling some of the Ceremonies will prevent progression in Totemic.
	#Example: ["totemic:rain", "totemic:drought"]
	#See the Totempedia with advanced tooltips enabled (F3+H) to look up the Ceremonies' IDs.
	disabledCeremonies = []
	#List of Totem Carvings that should be disabled from being carved.
	#Example: ["totemic:spider"]
	#Use advanced tooltips (F3+H) to look up the Totem Carvings' IDs.
	disabledTotemCarvings = []
	#List of Totem Carvings that may not be used in Medicine Bags.
	#Example: ["totemic:spider"]
	medicineBagBlacklist = []
	#The Ceremony startup time is multiplied by this value in Peaceful and Easy difficulty.
	#Higher values make Ceremonies easier to perform.
	#Default value: 1.1
	# Default: 1.1
	# Range: 0.1 ~ Infinity
	ceremonyStartupTimeMultiplierEasy = 1.1
	#The Ceremony startup time is multiplied by this value in Normal difficulty.
	#Default value: 1.0
	# Default: 1.0
	# Range: 0.1 ~ Infinity
	ceremonyStartupTimeMultiplierNormal = 1.0
	#The Ceremony startup time is multiplied by this value in Hard difficulty.
	#Default value: 0.875
	# Default: 0.875
	# Range: 0.1 ~ Infinity
	ceremonyStartupTimeMultiplierHard = 0.875
